In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5,6,7,8,9,10])

In [9]:
print("The sum of the arrays",np.sum(array1))

The sum of the arrays 55


In [10]:
print("The mean value of the array is:",np.mean(array1))

The mean value of the array is: 5.5


In [11]:
print("The max value of the array is:",np.max(array1))

The max value of the array is: 10


In [12]:
print("The minimum value of the array is:",np.min(array1))


The minimum value of the array is: 1


In [16]:
print("The reshape of the array \n ",array1.reshape(2,5))

The reshape of the array 
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
print("Adding the 5 using broadcasting \n",array1+5)

Adding the 5 using broadcasting 
 [ 6  7  8  9 10 11 12 13 14 15]


In [2]:
even_array=array1
if (even_array%2==0):
    print(array1)
else:
    print("We dont have even numbers")



NameError: name 'array1' is not defined