In [7]:
import numpy as np

In [8]:
array1=np.array([1,2,3,4,5,6,7,8,9,10])

In [9]:
print("The sum of the arrays",np.sum(array1))

The sum of the arrays 55


In [10]:
print("The mean value of the array is:",np.mean(array1))

The mean value of the array is: 5.5


In [11]:
print("The max value of the array is:",np.max(array1))

The max value of the array is: 10


In [12]:
print("The minimum value of the array is:",np.min(array1))


The minimum value of the array is: 1


In [13]:
print("The reshape of the array \n ",array1.reshape(2,5))

The reshape of the array 
  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
print("Adding the 5 using broadcasting \n",array1+5)

Adding the 5 using broadcasting 
 [ 6  7  8  9 10 11 12 13 14 15]


In [15]:
array1 = [1, 2, 3, 4, 5, 6]

even_array = []

for num in array1:
    if num % 2 == 0:
        even_array.append(num)

if even_array:
    print(even_array)
else:
    print("We dont have even numbers")


[2, 4, 6]


In [16]:
# Create arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise multiplication
element_wise = a * b

# Dot product
dot_product = np.dot(a, b)

# Print results
print("Array a:", a)
print("Array b:", b)

print("Element-wise multiplication:", element_wise)
print("Dot product:", dot_product)

Array a: [1 2 3]
Array b: [4 5 6]
Element-wise multiplication: [ 4 10 18]
Dot product: 32
