In [6]:
import numpy as np #we use allias as an np

In [7]:

arr1 = np.array([1, 2, 3, 4, 5])  # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array

print(arr1)  
print(arr2)  

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [8]:
#here i have created the examples of arrays.

In [9]:
#we will be creating the array where there's is only zeros.

In [12]:
zero_arr1 = np.zeros((3,4)) # 3 ota rows and 4 ota columns.

In [13]:
print(zero_arr1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
sequenced_array = np.arange(0,10,2)

In [15]:
print(sequenced_array)

[0 2 4 6 8]


In [16]:
traffic = np.array([500,600,500,600,555,1200])


In [20]:
weekend_traffic=traffic[-6:-1]

In [21]:
print(weekend_traffic)

[500 600 500 600]


In [22]:
sensors=np.array([
    [12.1,14.3,23.1,11.1],
    [22.2,69.1,23.1,22.2],
    [14.2,12.2,12.2,12.2],
    [22.2,33.2,22.3,77.7]
])
    

In [24]:
specific_reading=sensors[2,1]
print(specific_reading)

12.2


In [25]:
top_sensors=sensors[0:2,:]
print(top_sensors)

[[12.1 14.3 23.1 11.1]
 [22.2 69.1 23.1 22.2]]


In [28]:
final_readings=sensors[:,2]
print(final_readings)

[23.1 23.1 12.2 22.3]


In [31]:
flat_temps = np.array([22,24,35,23,23,45,46,44,32,89,12,89])
structured_temps = flat_temps.reshape(4,3)
print("The reshaped temperatures data is\n", structured_temps)


The reshaped temperatures data is
 [[22 24 35]
 [23 23 45]
 [46 44 32]
 [89 12 89]]


In [33]:
fahrenheit_temps=(structured_temps*9/5)+32
print(fahrenheit_temps)

[[ 71.6  75.2  95. ]
 [ 73.4  73.4 113. ]
 [114.8 111.2  89.6]
 [192.2  53.6 192.2]]


In [ ]:
#we have converted the temperature here


In [45]:
#axis
students= np.array([
    [23,23,45],
    [56,78,56],
    [77,88,99]
])
print("Overall highest score in the class",np.max(students))
print("Overall average score",np.mean(students))


Overall highest score in the class 99
Overall average score 60.55555555555556


In [39]:
subject_average = np.mean(students,axis=0)
print(subject_average)

[52.         63.         66.66666667]


In [40]:
student_averages=np.mean(students,axis=1)
print(student_averages)

[30.33333333 63.33333333 88.        ]


In [41]:
import time
size=1_00_000
python_list=list(range(size))
numpy_array=np.arange(size)

In [43]:
# print(python_list,numpy_array)

In [44]:
start_time=time.time()
python_list_result=[x*2 for x in python_list]
python_duration=time.time()-start_time

In [46]:
# python_duration=time.time()-start_time


In [47]:
start_time=time.time()
numpy_array_result=numpy_array*2
numpy_duration=time.time()-start_time


In [48]:
# #here i will be printing the time.
# print(f"Time taken by standard Python list:(python_duration:,.5f) seconds")
# print(f"Time taken by numpy array:(numpy_duration:.5f) seconds")
# print(f"Numpy is roughly (round(python_duration/numpy_duration))

SyntaxError: unterminated f-string literal (detected at line 4) (1675327832.py, line 4)