In [2]:
 import numpy as np


In [3]:
arr=np.array([1,2,3])

In [4]:
np.zeros((3, 3))    # 3x3 array of zeros


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr

array([1, 2, 3])

In [6]:
arr.ndim

1

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr.size

3

In [14]:
arr.shape

(3,)

In [15]:
#to change the datatype of the array
arr=np.array([1,2,3],dtype=np.float32)#Explicit type
print(arr.dtype)

float32


In [16]:
arr_int=arr.astype(np.int32) #converts float into int
print(arr_int)

[1 2 3]


In [17]:
#efficient memory usage by choosing te right data types.


In [18]:
arr=np.array([[1,2,3],[2,3,4]])
print(arr.shape)


(2, 3)


In [19]:
reshaped=arr.reshape((3,2)) #change the shape
print(reshaped)

[[1 2]
 [3 2]
 [3 4]]
